#!/usr/bin/env python3
"""
Windows Development Startup Script for Veterinary Clinic Management SaaS
This script sets up the development environment and starts the application.
"""

import os
import sys
import subprocess
import json
from pathlib import Path

def check_requirements():
    """Check if required tools are installed"""
    tools_to_check = [
        ('node', '--version', 'Node.js is required. Install from https://nodejs.org/'),
        ('npm', '--version', 'npm is required. Usually comes with Node.js'),
    ]
    
    missing = []
    for tool, flag, message in tools_to_check:
        try:
            # Try multiple common version flags on Windows
            version_flags = ['--version', '-v', '-V']
            detected = False
            
            for vflag in version_flags:
                try:
                    result = subprocess.run([tool, vflag], capture_output=True, text=True, timeout=10)
                    if result.returncode == 0 and result.stdout.strip():
                        version = result.stdout.strip().split('\n')[0]
                        print(f"✅ {tool} is installed (version: {version})")
                        detected = True
                        break
                except subprocess.TimeoutExpired:
                    continue
                except:
                    continue
            
            if not detected:
                print(f"❌ {message}")
                print(f"   Debug: Failed to get version for {tool}")
                missing.append(tool)
                
        except FileNotFoundError:
            print(f"❌ {message}")
            missing.append(tool)
    
    # Special Windows npm check - try with .cmd extension
    if 'npm' in missing:
        try:
            result = subprocess.run(['npm.cmd', '--version'], capture_output=True, text=True, timeout=10)
            if result.returncode == 0 and result.stdout.strip():
                version = result.stdout.strip().split('\n')[0]
                print(f"✅ npm is installed via npm.cmd (version: {version})")
                missing.remove('npm')
        except:
            pass
    
    if missing:
        print(f"\n❌ Missing required tools: {', '.join(missing)}")
        print("   💡 Tip: Try restarting your terminal or checking your PATH environment variable")
        return False
    return True

def setup_environment():
    """Set up environment variables for Windows development"""
    env_vars = {
        'NODE_ENV': 'development',
        'PORT': '5000',
        'CORS_ORIGIN': 'http://localhost:5000',
        # Replit environment variables for local development
        'REPLIT_DOMAINS': 'localhost:5000',
        'REPL_ID': 'local-development',
        'REPL_SLUG': 'veterinary-clinic-local',
        'REPL_OWNER': 'local-user',
        # Local authentication bypass
        'LOCAL_DEVELOPMENT': 'true',
    }
    
    # Load existing environment variables
    env_file = Path('.env')
    if env_file.exists():
        print("📄 Loading existing .env file...")
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.strip().startswith('#'):
                    key, value = line.strip().split('=', 1)
                    env_vars[key] = value
    else:
        print("⚠️  No .env file found. Creating with defaults...")
        
    # Ensure DATABASE_URL is set
    if 'DATABASE_URL' not in env_vars:
        print("⚠️  DATABASE_URL not found in environment")
        supabase_url = input("Enter your Supabase DATABASE_URL (or press Enter to skip): ").strip()
        if supabase_url:
            env_vars['DATABASE_URL'] = supabase_url
    
    # Write .env file for Windows
    with open('.env', 'w') as f:
        f.write("# Veterinary Clinic SaaS - Windows Development Environment\n")
        f.write("# Generated by start.py\n\n")
        for key, value in env_vars.items():
            f.write(f"{key}={value}\n")
    
    print("✅ Environment configured for Windows development")
    return env_vars

def install_dependencies():
    """Install npm dependencies"""
    print("📦 Installing npm dependencies...")
    
    # Try different npm commands for Windows compatibility
    npm_commands = ['npm', 'npm.cmd', 'npx', 'npx.cmd']
    
    for npm_cmd in npm_commands:
        try:
            print(f"   Trying: {npm_cmd} install...")
            result = subprocess.run([npm_cmd, 'install'], capture_output=True, text=True, check=True, timeout=300)
            print("✅ Dependencies installed successfully")
            return True
        except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired) as e:
            print(f"   Failed with {npm_cmd}: {e}")
            continue
    
    print("❌ Failed to install dependencies with any npm command")
    print("💡 Try running 'npm install' manually in your terminal")
    return False

def setup_database():
    """Set up database for development"""
    print("🗄️  Setting up database...")
    
    # Try different npm/npx commands for Windows
    npx_commands = ['npx', 'npx.cmd', 'npm', 'npm.cmd']
    
    for npx_cmd in npx_commands:
        try:
            print(f"   Trying: {npx_cmd} drizzle-kit push...")
            if npx_cmd.startswith('npm'):
                result = subprocess.run([npx_cmd, 'run', 'db:push'], capture_output=True, text=True, check=True, timeout=120)
            else:
                result = subprocess.run([npx_cmd, 'drizzle-kit', 'push'], capture_output=True, text=True, check=True, timeout=120)
            print("✅ Database schema pushed successfully")
            return True
        except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired) as e:
            print(f"   Failed with {npx_cmd}: {e}")
            continue
    
    print("⚠️  Database setup failed with all commands")
    print("💡 Try running 'npm run db:push' manually in your terminal")
    return False

def start_development_server():
    """Start the development server with proper environment"""
    print("🚀 Starting development server...")
    print("Server will be available at: http://localhost:5000")
    print("Press Ctrl+C to stop the server\n")
    
    try:
        # Load environment variables from .env file and set them explicitly
        env_file = Path('.env')
        env_vars = {}
        if env_file.exists():
            with open(env_file, 'r') as f:
                for line in f:
                    if '=' in line and not line.strip().startswith('#'):
                        key, value = line.strip().split('=', 1)
                        env_vars[key] = value
        
        # Merge with system environment
        full_env = {**os.environ, **env_vars}
        
        # Use cross-env to ensure environment variables work on Windows
        # Force local development mode to bypass Replit authentication
        
        # Try different npm/npx commands for Windows
        npm_commands = ['npx', 'npx.cmd', 'npm', 'npm.cmd']
        server_started = False
        
        for npm_cmd in npm_commands:
            try:
                print(f"   Trying to start server with: {npm_cmd}...")
                if npm_cmd.startswith('npm'):
                    result = subprocess.run([
                        npm_cmd, 'run', 'dev'
                    ], env=full_env, check=True)
                else:
                    result = subprocess.run([
                        npm_cmd, 'cross-env',
                        'NODE_ENV=development',
                        'LOCAL_DEVELOPMENT=true',
                        'REPLIT_DOMAINS=localhost:5000',
                        'REPL_ID=local-development',
                        npm_cmd, 'tsx', 'server/index.ts'
                    ], env=full_env, check=True)
                server_started = True
                break
            except (subprocess.CalledProcessError, FileNotFoundError) as e:
                print(f"   Failed with {npm_cmd}: {e}")
                continue
        
        if not server_started:
            print("❌ Failed to start server with any npm command")
            print("💡 Try running 'npm run dev' manually in your terminal")
            return False
    except subprocess.CalledProcessError as e:
        print(f"❌ Server failed to start: {e}")
        return False
    except KeyboardInterrupt:
        print("\n🛑 Server stopped by user")
        return True

def main():
    """Main startup sequence"""
    print("🏥 Veterinary Clinic Management SaaS - Windows Development Setup")
    print("=" * 60)
    
    # Check requirements
    if not check_requirements():
        sys.exit(1)
    
    # Setup environment
    env_vars = setup_environment()
    
    # Install dependencies
    if not install_dependencies():
        sys.exit(1)
    
    # Setup database
    setup_database()
    
    # Start server
    start_development_server()

if __name__ == "__main__":
    main()